// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/nodemgr/nodemgr.proto

package nodemgr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStreamRequest) Reset() {
	*x = HealthStreamRequest{}
	mi := &file_proto_nodemgr_nodemgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStreamRequest) ProtoMessage() {}

func (x *HealthStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodemgr_nodemgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStreamRequest.ProtoReflect.Descriptor instead.
func (*HealthStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_nodemgr_nodemgr_proto_rawDescGZIP(), []int{0}
}

func (x *HealthStreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HealthEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs         int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	Timestamp         int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthEvent) Reset() {
	*x = HealthEvent{}
	mi := &file_proto_nodemgr_nodemgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvent) ProtoMessage() {}

func (x *HealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodemgr_nodemgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvent.ProtoReflect.Descriptor instead.
func (*HealthEvent) Descriptor() ([]byte, []int) {
	return file_proto_nodemgr_nodemgr_proto_rawDescGZIP(), []int{1}
}

func (x *HealthEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthEvent) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *HealthEvent) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *HealthEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_nodemgr_nodemgr_proto protoreflect.FileDescriptor

const file_proto_nodemgr_nodemgr_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/nodemgr/nodemgr.proto\x12\anodemgr\".\n" +
	"\x13HealthStreamRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xaa\x01\n" +
	"\vHealthEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x03R\x11activeConnections\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2Y\n" +
	"\x11NodeHealthService\x12D\n" +
	"\fStreamHealth\x12\x1c.nodemgr.HealthStreamRequest\x1a\x14.nodemgr.HealthEvent0\x01B\x1fZ\x1dgo-node-manager/proto/nodemgrb\x06proto3"

var (
	file_proto_nodemgr_nodemgr_proto_rawDescOnce sync.Once
	file_proto_nodemgr_nodemgr_proto_rawDescData []byte
)

func file_proto_nodemgr_nodemgr_proto_rawDescGZIP() []byte {
	file_proto_nodemgr_nodemgr_proto_rawDescOnce.Do(func() {
		file_proto_nodemgr_nodemgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nodemgr_nodemgr_proto_rawDesc), len(file_proto_nodemgr_nodemgr_proto_rawDesc)))
	})
	return file_proto_nodemgr_nodemgr_proto_rawDescData
}

var file_proto_nodemgr_nodemgr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_nodemgr_nodemgr_proto_goTypes = []any{
	(*HealthStreamRequest)(nil), // 0: nodemgr.HealthStreamRequest
	(*HealthEvent)(nil),         // 1: nodemgr.HealthEvent
}
var file_proto_nodemgr_nodemgr_proto_depIdxs = []int32{
	0, // 0: nodemgr.NodeHealthService.StreamHealth:input_type -> nodemgr.HealthStreamRequest
	1, // 1: nodemgr.NodeHealthService.StreamHealth:output_type -> nodemgr.HealthEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_nodemgr_nodemgr_proto_init() }
func file_proto_nodemgr_nodemgr_proto_init() {
	if File_proto_nodemgr_nodemgr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nodemgr_nodemgr_proto_rawDesc), len(file_proto_nodemgr_nodemgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nodemgr_nodemgr_proto_goTypes,
		DependencyIndexes: file_proto_nodemgr_nodemgr_proto_depIdxs,
		MessageInfos:      file_proto_nodemgr_nodemgr_proto_msgTypes,
	}.Build()
	File_proto_nodemgr_nodemgr_proto = out.File
	file_proto_nodemgr_nodemgr_proto_goTypes = nil
	file_proto_nodemgr_nodemgr_proto_depIdxs = nil
}
