// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/nodemgr/nodemgr.proto

package nodemgr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeHealthService_StreamHealth_FullMethodName = "/nodemgr.NodeHealthService/StreamHealth"
)

// NodeHealthServiceClient is the client API for NodeHealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeHealthServiceClient interface {
	StreamHealth(ctx context.Context, in *HealthStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthEvent], error)
}

type nodeHealthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeHealthServiceClient(cc grpc.ClientConnInterface) NodeHealthServiceClient {
	return &nodeHealthServiceClient{cc}
}

func (c *nodeHealthServiceClient) StreamHealth(ctx context.Context, in *HealthStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeHealthService_ServiceDesc.Streams[0], NodeHealthService_StreamHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HealthStreamRequest, HealthEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeHealthService_StreamHealthClient = grpc.ServerStreamingClient[HealthEvent]

// NodeHealthServiceServer is the server API for NodeHealthService service.
// All implementations must embed UnimplementedNodeHealthServiceServer
// for forward compatibility.
type NodeHealthServiceServer interface {
	StreamHealth(*HealthStreamRequest, grpc.ServerStreamingServer[HealthEvent]) error
	mustEmbedUnimplementedNodeHealthServiceServer()
}

// UnimplementedNodeHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeHealthServiceServer struct{}

func (UnimplementedNodeHealthServiceServer) StreamHealth(*HealthStreamRequest, grpc.ServerStreamingServer[HealthEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamHealth not implemented")
}
func (UnimplementedNodeHealthServiceServer) mustEmbedUnimplementedNodeHealthServiceServer() {}
func (UnimplementedNodeHealthServiceServer) testEmbeddedByValue()                           {}

// UnsafeNodeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeHealthServiceServer will
// result in compilation errors.
type UnsafeNodeHealthServiceServer interface {
	mustEmbedUnimplementedNodeHealthServiceServer()
}

func RegisterNodeHealthServiceServer(s grpc.ServiceRegistrar, srv NodeHealthServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeHealthService_ServiceDesc, srv)
}

func _NodeHealthService_StreamHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeHealthServiceServer).StreamHealth(m, &grpc.GenericServerStream[HealthStreamRequest, HealthEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeHealthService_StreamHealthServer = grpc.ServerStreamingServer[HealthEvent]

// NodeHealthService_ServiceDesc is the grpc.ServiceDesc for NodeHealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeHealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodemgr.NodeHealthService",
	HandlerType: (*NodeHealthServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHealth",
			Handler:       _NodeHealthService_StreamHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/nodemgr/nodemgr.proto",
}
